USE SCHEMA CURRENT_RAW;

CREATE OR REPLACE VIEW FXRATES 
COMMENT = 'VIEW TO FETCH THE MOST RECENT RECORDS' 
AS
SELECT
PRIMARY_KEY,
EXCHANGE_SOURCE_CODE,
CURRENCY_PAIR_CODE,
EFFECTIVE_DATE,
SPOT_RATE,
SOURCE_FILENAME,
INGESTION_TIME
FROM
    (
        SELECT
            *,
            ROW_NUMBER() OVER(
                PARTITION BY 
                EXCHANGE_SOURCE_CODE,
                CURRENCY_PAIR_CODE,
                EFFECTIVE_DATE
                ORDER BY
                    INGESTION_TIME DESC
            ) AS RN
        FROM
            RAW.FXRATES
    )
WHERE
    RN = 1
ORDER BY
    EXCHANGE_SOURCE_CODE,
    CURRENCY_PAIR_CODE,
    EFFECTIVE_DATE,
    INGESTION_TIME;