version: 2

sources:
  - name: PUBLIC
    schema: PUBLIC
    tables:
      - name: ACCOUNTPROFILE
      - name: ACCOUNTSECURITIES
      - name: CHARACTERISTICS
      - name: CLASSIFICATIONS
      - name: COUNTRYCALENDAR
      - name: FXRATES
      - name: HOLDINGS
      - name: INDEXSECURITY
      - name: INDEXTOTAL
      - name: PORTFOLIONODE
      - name: PORTFOLIOTOTAL
      - name: SMF
      - name: SPONSORBENCHMARK
      - name: TRANSACTIONS
